name: Auto-merge l10n pull requests

on:
  repository_dispatch:
    types:
      - "vercel.deployment.success"
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'l10n_main' && github.event.pull_request.merged == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto-merge pull request
        run: gh pr merge --squash --auto ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
